<?php

use App\Controllers\MainController;

class IndexController extends MainController
{
	protected function input()
	{
		parent::input(); // TODO: Change the autogenerated stub

		$this->title .= "Главная";
	}

	protected function output()
	{
		$this->content = $this->render('App\View\main');
		$this->page = parent::output(); // TODO: Change the autogenerated stub

		return $this->page;

	}

}
