<?php
/**
 * Created by PhpStorm.
 * User: Evgeniy
 * Date: 21.09.2016
 * Time: 22:03
 */

namespace App\Controllers;


use App\Model;
use App\Models\News;
use App\DB;

abstract class MainController extends Controller
{
    //object model
    protected $obmod;

    protected $title;

    protected $header;

    protected $headmenu;

    protected $content;

    protected $footer;

    protected function input()
    {
        $this->title = "Sport Zal / ";
        $this->obmod = News::findAll();
        var_dump($this->obmod);
    }

    protected function output()
    {
        $this->header = $this->render('App\View\header');
        $this->footer = $this->render('App\View\footer');

        $page = $this->render('App\View\index',['header'=>$this->header,'content'=>$this->content,'footer'=>$this->footer]);

        return $page;
        //parent::output(); // TODO: Change the autogenerated stub
    }


}