<?php
/**
 * Created by PhpStorm.
 * User: Evgeniy
 * Date: 21.09.2016
 * Time: 22:03
 */

namespace App\Controllers;

use App\Models\News;

abstract class MainController extends Controller
{
    //object model
    protected $obmod;

    protected $title;

    protected $header;

    protected $headmenu;

    protected $content;

    protected $footer;

    protected $news;

    protected function input()
    {
        $this->title = "Sport Zal / ";
        $this->news = News::findAll();

    }

    protected function output()
    {
        $this->header = $this->render('App\View\header');
        $this->content = $this->render('App\View\main', ['news' => $this->news]);
        $this->footer = $this->render('App\View\footer');

        $page = $this->render('App\View\index',['header'=>$this->header,'content'=>$this->content,'footer'=>$this->footer]);

        return $page;
        //parent::output(); // TODO: Change the autogenerated stub
    }


}